### ISSUE TITLE
Installation fails on CentOS 6 (libtool, old autoconf, old node version)

### ISSUE THREAD

**Issue by slrslr** [creationix/drop-dat#3]
Hello, on CentOS 6.10 64bit i tried: # npm install -g drop-dat
And it shown warnings and then failed to start drop-dat. [Here is](https://defuse.ca/b/I6MBAYcTyDnm6TytfZErHx) full terminal output. The pwd is: dat
Thank You

**Comment by Fastidious** [comment]
Start here: 

`libtool is required, but wasn't found on this system`

CentOS 6.10 is quite old.

**Comment by slrslr** [comment]
So i installed libtool by: yum install libtool
Then installation of drop-dat mentioned "error: Autoconf version 2.65 or higher is required"
I had lower version, so i did: wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.68.tar.gz; tar zxf autoconf-2.68.tar.gz; cd autoconf-2.68;./configure;make;make install
Then installer says: "configure.ac: not using Gettext"
I tried: yum install gettext
But that not removed the gettext error. Do you have any idea which command to run to fix it?

**Comment by Fastidious** [comment]
@slrslr I would love to help, but as you are running a relatively old OS you will find yourself at cross roads like these. Manually installing packages will also become a nightmare. I recommend you switch to a newer OS perhaps? Is that something viable?

**Comment by slrslr** [comment]
It is not 6.1, but 6.10 which should be latest version of the supported OS until winter 2020. https://wiki.centos.org/Download
I read sometimes is suggested to do "yum groupinstall Development tools"
But it wants to DL quite alot of data that mostly would not be necessary:
Total download size: 56 M
Installed size: 177 M
But since we do not know which packages are necessary or how to install them, i installed that software group. But that not helped. npm install [continue to fail](https://pastebin.com/LuP9pct9) and when running "drop-dat" it says:
```
/usr/lib/node_modules/drop-dat/node_modules/promisey/promisey.js:52
exports.C = async (fn, ...args) => fn(...args)
                  ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/drop-dat/drop-dat.es5.js:15:16)
```

If you can not solve this, please close it, maybe later someone reply knowing solution. Thank you

**Comment by Fastidious** [comment]
@slrslr what `node -v` renders?

**Comment by slrslr** [comment]
@Fastidious v6.14.4

**Comment by slrslr** [comment]
@Fastidious 

I tried to update to newest node version **and IT WORKED**:

   14  node -v
v6.14.4
   17  npm install -g n
   18  n stable
   25  ls /usr/local/n/versions/node/*/bin/node
/usr/local/n/versions/node/10.8.0/bin/node
   27  ln -sf /usr/local/n/versions/node/10.8.0/bin/node /usr/bin/node
   28  node -v
v10.8.0
   29  npm uninstall -g drop-dat
   30  npm install -g drop-dat
   31  drop-dat
Usage: drop-dat files...

Then i shared the file:
drop-dat ./vzdump-1.log
Importing file(s):
  vzdump-1.log
Sharing on P2P network
Sharing on dat P2P network...
Press Control+C to stop sharing.

dat://hashhere

On remote internet PC i did: dat clone dat://hashhere

Within like 30 seconds it connected and downloaded the file :) !!

Can drop-dat installation be made to return some more user friendly error on the end of the output so user knows he need to upgrade nodejs(?)? Or even a suggestion how to upgrade it?

**Comment by joehand** [comment]
> Can drop-dat installation be made to return some more user friendly error on the end of the output so user knows he need to upgrade nodejs(?)? Or even a suggestion how to upgrade it?

This project was mostly a demo and is likely not maintained anymore. You could help others who run into the problem by changing the issue title to something about old node versions.

**Comment by slrslr** [comment]
thank you
